name: Mozilla Reps - Coaching skills training
description: This website contains resources needed by Mozilla Reps to became Mentors
baseurl: ''

collections:
 lessons:
   output: true
categories: [course, resource]
